### PR TITLE
Initialize Checkbox base component, tested in stage route

### PR DESCRIPTION
**Pull request by Enixun**
Structure is similar to Radio base component, should we consider combining into a single generic base component?

Co-authored-by: Stefan Jordan <sjordan2010@gmail.com>
Co-authored-by: Johnny Howell <tsjohnnyh@gmail.com>
Co-authored-by: Ksenia <45905849+ksslv@users.noreply.github.com>
Co-authored-by: Umair Shafiq <soulofstorms@hotmail.com>

### CODE REVIEW

**Review by mooselamb — APPROVED** [review]
Good work

**Review by ksslv — APPROVED** [review]
Looks good.

**Review by sjordan2010 — APPROVED** [review]
Great job!

**Comment by Loudhouse-Dev** [comment]
Thumbs Up

**Pull request merged**
